### PR TITLE
My first pull request

### PR DESCRIPTION
**Pull request by brainconnect93**
I started the project by creating 
1.  A hello Microverse HTML file
2. A hello Microverse CSS file
3. Installed the Linters file
4. Fixed Linters error

### CODE REVIEW

**Comment by chrystalme** [comment]
Hi @brainconnect93,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❗ 

You have submitted a project that contains Linter errors. Please, check the failing errors and try to fix them before submitting another review request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by CollinsTatang — CHANGES_REQUESTED** [review]
Hi @brainconnect93, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:

## Required Changes ♻️

- [ ] Please kindly add [README](https://github.com/microverseinc/readme-template) to your project.
- [ ] Kindly add a [descriptive summary pull request](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to your project.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by brainconnect93** [comment]
I did this to show I can use basic HTML and CSS semantics, also to send a message to all other coders

**Review by mahbubul14 — CHANGES_REQUESTED** [review]
Hi @brainconnect93 ,

Great work on attempting to make the changes requested by a previous reviewer :clap: 
You've done well building this project, but there are some issues that you still need to work on to go to the next project.

# Required Changes ♻️

- [ ]  Currently, your readme file is not descriptive enough. Please update your readme file. You can use [this template ](https://github.com/microverseinc/readme-template) but remember to customize it according to your project and personal info.

- [ ] As the previous reviewer said, Pull Request should have a short summary describing introduced changes in more detail. You can check rule no. 2 from [this link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to get an idea. Please work on that.
s1

###  To Highlights
:heavy_check_mark: No linters error.
:heavy_check_mark: Github flow used properly.

### Optional suggestions

- [ ] Please add `test.md` in the `.gitignore` file. This is a mandatory requirement for this project. As you previous reviewer didn't suggest that change, that's why I kept it optional.

- [ ] The commit message should be written in the imperative tense. `Ex: "Fix bug" instead of "Fixing bug".` [For more details.](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Review by phelian23 — APPROVED** [review]
Hi @brainconnect93, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
